version: '3.8'

services:
    php:
        user: ${DOCKER_USER}
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${PROJECT_DOMAIN}`)"
            # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-opened-api.rule=Host(`${PROJECT_DOMAIN}`) && (PathPrefix(`/api/`) || PathPrefix(`/media/`))"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=default"
            # - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=auth"

    database:
        volumes:
            - /web/data/$COMPOSE_PROJECT_NAME/mysql:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        environment:
            ADMINER_DEFAULT_SERVER: database
            ADMINER_DESIGN: hydra
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-adminer.rule=Host(`${ADMINER_DOMAIN}`)"
            - "traefik.http.services.${COMPOSE_PROJECT_NAME}-adminer.loadbalancer.server.port=8080"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-adminer.tls.certresolver=default"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-adminer.middlewares=auth"