version: '3.8'

services:
    php:
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${PROJECT_DOMAIN}`)"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-opened-api.rule=Host(`${PROJECT_DOMAIN}`) && (PathPrefix(`/api/`) || PathPrefix(`/media/`))"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=default"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=auth"

    database:
        volumes:
            - /web/data/$COMPOSE_PROJECT_NAME/mysql:/var/lib/mysql