version: '3.8'

services:
    php:
        image: yiisoftware/yii2-php:7.4-apache
        volumes:
            - ./tmp/.composer/cache:/root/.composer/cache:delegated
            - ./:/app:delegated

    database:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}